---
title: Mouse ileum cell interactions
vignette: >
  % \VignetteIndexEntry{Mouse ileum cell interactions}
  % \VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
output:
  html_document:
    mathjax: null   
---

# Setup

```{r, message = FALSE, warning = FALSE}
library(MerfishData)
library(ExperimentHub)
library(imcRtools)
```

# Data retrieval

```{r ehub}
eh <- ExperimentHub()
query(eh, c("MerfishData", "ileum"))
```

```{r spe-ileum, message = FALSE}
spe <- MerfishData::MouseIleumPetukhov2021(segmentation = "baysor",
                                           use.images = FALSE,
                                           use.polygons = FALSE)
spe
```

# Spatial proximity analysis

```{r}
spe <- imcRtools::buildSpatialGraph(spe,
                                    img_id = "sample_id",
                                    type = "knn",
                                    k = 5, 
                                    coords = c("x", "y")) 
colPairs(spe)
colPairs(spe)[[1]]
```


```{r}
ia.counts <- imcRtools::countInteractions(spe,
                                          group_by = "sample_id",
                                          label = "leiden_final",
                                          colPairName = "knn_interaction_graph",
                                          method = "classic")
ia.counts
```

```{r}
ia.sig <- imcRtools::testInteractions(spe,
                                      group_by = "sample_id",
                                      label = "leiden_final",
                                      colPairName = "knn_interaction_graph",
                                      method = "classic")
ia.sig
```

# Ligand-receptor co-expression analysis

# Ligand-target co-expression analysis
